/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import com.google.gson.*;
import java.util.Random;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

public class App {

    public static void main(String[] args) throws IOException {
        Path quotePath = Paths.get("recentquotes.json");
        gson(quotePath);
    }


    public static int gson(Path file) throws IOException {

        try (Reader reader = Files.newBufferedReader(file, StandardCharsets.UTF_8)) {

            JsonElement author = JsonParser.parseReader(reader);

            JsonArray array = author.getAsJsonArray();

            Random random = new Random();
            int q = random.nextInt(array.size());

            JsonElement element = array.get(q);


            if (element.isJsonObject()) {
                JsonObject book = element.getAsJsonObject();
                System.out.println(book.get("author").getAsString());
                System.out.println(book.get("text").getAsString());
            }
            return q;
        }
    }
}